// Mocks generated by Mockito 5.4.6 from annotations
// in cambridge_beer_festival/test/provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cambridge_beer_festival/models/models.dart' as _i5;
import 'package:cambridge_beer_festival/services/beer_api_service.dart' as _i3;
import 'package:cambridge_beer_festival/services/festival_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFestivalsResponse_1 extends _i1.SmartFake
    implements _i2.FestivalsResponse {
  _FakeFestivalsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BeerApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeerApiService extends _i1.Mock implements _i3.BeerApiService {
  MockBeerApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  _i4.Future<List<_i5.Drink>> fetchDrinks(
    _i5.Festival? festival,
    String? beverageType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDrinks,
          [
            festival,
            beverageType,
          ],
        ),
        returnValue: _i4.Future<List<_i5.Drink>>.value(<_i5.Drink>[]),
      ) as _i4.Future<List<_i5.Drink>>);

  @override
  _i4.Future<List<_i5.Drink>> fetchAllDrinks(_i5.Festival? festival) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllDrinks,
          [festival],
        ),
        returnValue: _i4.Future<List<_i5.Drink>>.value(<_i5.Drink>[]),
      ) as _i4.Future<List<_i5.Drink>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FestivalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFestivalService extends _i1.Mock implements _i2.FestivalService {
  MockFestivalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  _i4.Future<_i2.FestivalsResponse> fetchFestivals() => (super.noSuchMethod(
        Invocation.method(
          #fetchFestivals,
          [],
        ),
        returnValue:
            _i4.Future<_i2.FestivalsResponse>.value(_FakeFestivalsResponse_1(
          this,
          Invocation.method(
            #fetchFestivals,
            [],
          ),
        )),
      ) as _i4.Future<_i2.FestivalsResponse>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
