// Mocks generated by Mockito 5.4.6 from annotations
// in cambridge_beer_festival/test/provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cambridge_beer_festival/domain/repositories/drink_repository.dart'
    as _i5;
import 'package:cambridge_beer_festival/domain/repositories/festival_repository.dart'
    as _i8;
import 'package:cambridge_beer_festival/models/models.dart' as _i7;
import 'package:cambridge_beer_festival/services/analytics_service.dart' as _i9;
import 'package:cambridge_beer_festival/services/festival_service.dart' as _i2;
import 'package:firebase_analytics/firebase_analytics.dart' as _i3;
import 'package:firebase_crashlytics/firebase_crashlytics.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFestivalsResponse_0 extends _i1.SmartFake
    implements _i2.FestivalsResponse {
  _FakeFestivalsResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAnalytics_1 extends _i1.SmartFake
    implements _i3.FirebaseAnalytics {
  _FakeFirebaseAnalytics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseCrashlytics_2 extends _i1.SmartFake
    implements _i4.FirebaseCrashlytics {
  _FakeFirebaseCrashlytics_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DrinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDrinkRepository extends _i1.Mock implements _i5.DrinkRepository {
  @override
  _i6.Future<List<_i7.Drink>> getDrinks(_i7.Festival? festival) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDrinks,
          [festival],
        ),
        returnValue: _i6.Future<List<_i7.Drink>>.value(<_i7.Drink>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i7.Drink>>.value(<_i7.Drink>[]),
      ) as _i6.Future<List<_i7.Drink>>);

  @override
  _i6.Future<List<String>> getFavorites(String? festivalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [festivalId],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> toggleFavorite(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int?> getRating(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRating,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<int?>.value(),
        returnValueForMissingStub: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<void> setRating(
    String? festivalId,
    String? drinkId,
    int? rating,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            festivalId,
            drinkId,
            rating,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeRating(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeRating,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> hasTasted(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasTasted,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> toggleTasted(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleTasted,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<String>> getTastedDrinks(String? festivalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTastedDrinks,
          [festivalId],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<String?> getFavoriteStatus(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteStatus,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> markAsTasted(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsTasted,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTry(
    String? festivalId,
    String? drinkId,
    DateTime? timestamp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTry,
          [
            festivalId,
            drinkId,
            timestamp,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getTryCount(
    String? festivalId,
    String? drinkId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTryCount,
          [
            festivalId,
            drinkId,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
}

/// A class which mocks [FestivalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFestivalRepository extends _i1.Mock
    implements _i8.FestivalRepository {
  @override
  _i6.Future<_i2.FestivalsResponse> getFestivals() => (super.noSuchMethod(
        Invocation.method(
          #getFestivals,
          [],
        ),
        returnValue:
            _i6.Future<_i2.FestivalsResponse>.value(_FakeFestivalsResponse_0(
          this,
          Invocation.method(
            #getFestivals,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.FestivalsResponse>.value(_FakeFestivalsResponse_0(
          this,
          Invocation.method(
            #getFestivals,
            [],
          ),
        )),
      ) as _i6.Future<_i2.FestivalsResponse>);

  @override
  _i6.Future<String?> getSelectedFestivalId() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedFestivalId,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> setSelectedFestivalId(String? festivalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSelectedFestivalId,
          [festivalId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i9.AnalyticsService {
  @override
  _i3.FirebaseAnalytics get analytics => (super.noSuchMethod(
        Invocation.getter(#analytics),
        returnValue: _FakeFirebaseAnalytics_1(
          this,
          Invocation.getter(#analytics),
        ),
        returnValueForMissingStub: _FakeFirebaseAnalytics_1(
          this,
          Invocation.getter(#analytics),
        ),
      ) as _i3.FirebaseAnalytics);

  @override
  _i4.FirebaseCrashlytics get crashlytics => (super.noSuchMethod(
        Invocation.getter(#crashlytics),
        returnValue: _FakeFirebaseCrashlytics_2(
          this,
          Invocation.getter(#crashlytics),
        ),
        returnValueForMissingStub: _FakeFirebaseCrashlytics_2(
          this,
          Invocation.getter(#crashlytics),
        ),
      ) as _i4.FirebaseCrashlytics);

  @override
  _i6.Future<void> logAppLaunch() => (super.noSuchMethod(
        Invocation.method(
          #logAppLaunch,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logFestivalSelected(_i7.Festival? festival) =>
      (super.noSuchMethod(
        Invocation.method(
          #logFestivalSelected,
          [festival],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logSearch(String? query) => (super.noSuchMethod(
        Invocation.method(
          #logSearch,
          [query],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logCategoryFilter(String? category) => (super.noSuchMethod(
        Invocation.method(
          #logCategoryFilter,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logStyleFilter(Set<String>? styles) => (super.noSuchMethod(
        Invocation.method(
          #logStyleFilter,
          [styles],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logSortChange(String? sortType) => (super.noSuchMethod(
        Invocation.method(
          #logSortChange,
          [sortType],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logFavoriteAdded(_i7.Drink? drink) => (super.noSuchMethod(
        Invocation.method(
          #logFavoriteAdded,
          [drink],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logFavoriteRemoved(_i7.Drink? drink) => (super.noSuchMethod(
        Invocation.method(
          #logFavoriteRemoved,
          [drink],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logTastedAdded(_i7.Drink? drink) => (super.noSuchMethod(
        Invocation.method(
          #logTastedAdded,
          [drink],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logTastedRemoved(_i7.Drink? drink) => (super.noSuchMethod(
        Invocation.method(
          #logTastedRemoved,
          [drink],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logDrinkViewed(_i7.Drink? drink) => (super.noSuchMethod(
        Invocation.method(
          #logDrinkViewed,
          [drink],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logBreweryViewed(String? breweryName) => (super.noSuchMethod(
        Invocation.method(
          #logBreweryViewed,
          [breweryName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logStyleViewed(String? style) => (super.noSuchMethod(
        Invocation.method(
          #logStyleViewed,
          [style],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logRatingGiven(
    _i7.Drink? drink,
    int? rating,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logRatingGiven,
          [
            drink,
            rating,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logDrinkShared(_i7.Drink? drink) => (super.noSuchMethod(
        Invocation.method(
          #logDrinkShared,
          [drink],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logFestivalLogMarkTasted(
    String? drinkId,
    int? tryCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logFestivalLogMarkTasted,
          [
            drinkId,
            tryCount,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logFestivalLogMultipleTasting(
    String? drinkId,
    int? tryCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logFestivalLogMultipleTasting,
          [
            drinkId,
            tryCount,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logFestivalLogDeleteTimestamp(String? drinkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #logFestivalLogDeleteTimestamp,
          [drinkId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logError(
    Object? error,
    StackTrace? stackTrace, {
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logError,
          [
            error,
            stackTrace,
          ],
          {#reason: reason},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserProperty(
    String? name,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserProperty,
          [
            name,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
