/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1alpha/festivals/{festival}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all drinks the caller has bookmarked at a festival.
         *
         *      Intended for pre-loading "my festival" state on app open.
         */
        get: operations["MyFestivalService_ListBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/drinks/{drink}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description --- Bookmarks (caller-scoped singletons) ---------------------------------
         *      Get the caller's bookmark for a drink.
         */
        get: operations["MyFestivalService_GetBookmark"];
        put?: never;
        post?: never;
        /** @description Remove the caller's bookmark for a drink. */
        delete: operations["MyFestivalService_DeleteBookmark"];
        options?: never;
        head?: never;
        /** @description Create or update the caller's bookmark for a drink (upsert). */
        patch: operations["MyFestivalService_UpdateBookmark"];
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/drinks/{drink}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description --- Tasting notes (caller-scoped singletons) -----------------------------
         *      Get the caller's tasting note for a drink.
         */
        get: operations["MyFestivalService_GetNote"];
        put?: never;
        post?: never;
        /** @description Remove the caller's tasting note for a drink. */
        delete: operations["MyFestivalService_DeleteNote"];
        options?: never;
        head?: never;
        /** @description Create or update the caller's tasting note for a drink (upsert). */
        patch: operations["MyFestivalService_UpdateNote"];
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/drinks/{drink}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description --- Personal reviews (caller-scoped singletons) --------------------------
         *      Get the caller's review for a drink.
         */
        get: operations["MyFestivalService_GetReview"];
        put?: never;
        post?: never;
        /** @description Remove the caller's review for a drink. */
        delete: operations["MyFestivalService_DeleteReview"];
        options?: never;
        head?: never;
        /**
         * @description Create or update the caller's review for a drink (upsert).
         *
         *      Use `update_mask` to update a single signal (e.g. only `star_rating`)
         *      without clearing the other.
         */
        patch: operations["MyFestivalService_UpdateReview"];
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/drinks/{drink}/tasting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description --- Tasting log (caller-scoped singletons) -------------------------------
         *      Get the caller's tasting record for a drink.
         */
        get: operations["MyFestivalService_GetTasting"];
        put?: never;
        post?: never;
        /** @description Remove the caller's tasting record for a drink. */
        delete: operations["MyFestivalService_DeleteTasting"];
        options?: never;
        head?: never;
        /**
         * @description Create or update the caller's tasting record for a drink (upsert).
         *
         *      Use `update_mask` with `pours` to increment the pour count without
         *      affecting other fields.
         */
        patch: operations["MyFestivalService_UpdateTasting"];
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all tasting notes the caller has written at a festival. */
        get: operations["MyFestivalService_ListNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/reviewSummaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List aggregate review signals for every reviewed drink at a festival. */
        get: operations["MyFestivalService_ListReviewSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/reviewSummaries/{reviewSummary}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description --- Aggregates (public, not caller-scoped) --------------------------------
         *      Get the aggregate review signals for a single drink.
         */
        get: operations["MyFestivalService_GetReviewSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all reviews the caller has left for drinks at a festival.
         *
         *      Only the caller's own reviews are returned; caller identity is implicit in
         *      the auth context. Intended for pre-loading "my festival" state on app open.
         */
        get: operations["MyFestivalService_ListReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/tastingSummaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List tasting counts for every tried drink at a festival. */
        get: operations["MyFestivalService_ListTastingSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/tastingSummaries/{tastingSummary}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get tasting counts for a single drink. */
        get: operations["MyFestivalService_GetTastingSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1alpha/festivals/{festival}/tastings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all tasting records the caller has logged at a festival. */
        get: operations["MyFestivalService_ListTastings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A drink the caller has bookmarked at a festival.
         *
         *      Singleton resource — one per (caller, drink). The resource's mere existence
         *      means the drink is bookmarked; deleting it removes the bookmark. The caller
         *      is implicit in the auth context.
         */
        Bookmark: {
            /** @description Resource name: festivals/{festival}/drinks/{drink}/bookmark. */
            name?: string;
            /**
             * Format: date-time
             * @description When the bookmark was created.
             */
            readonly createTime?: string;
        };
        /** @description Response message for ListBookmarks. */
        ListBookmarksResponse: {
            /** @description The caller's bookmarks for this page, one per bookmarked drink. */
            bookmarks?: components["schemas"]["Bookmark"][];
            /** @description Token for the next page; empty when there are no more results. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of drinks the caller has bookmarked at this festival.
             */
            totalSize?: number;
        };
        /** @description Response message for ListNotes. */
        ListNotesResponse: {
            /** @description The caller's notes for this page, one per noted drink. */
            notes?: components["schemas"]["Note"][];
            /** @description Token for the next page; empty when there are no more results. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of drinks the caller has notes for at this festival.
             */
            totalSize?: number;
        };
        /** @description Response message for ListReviewSummaries. */
        ListReviewSummariesResponse: {
            /** @description Aggregate review signals for this page, one per reviewed drink. */
            reviewSummaries?: components["schemas"]["ReviewSummary"][];
            /** @description Token for the next page; empty when there are no more results. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of drinks with at least one review at this festival.
             */
            totalSize?: number;
        };
        /** @description Response message for ListReviews. */
        ListReviewsResponse: {
            /** @description The caller's reviews for this page, one per reviewed drink. */
            reviews?: components["schemas"]["Review"][];
            /** @description Token for the next page; empty when there are no more results. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of drinks the caller has reviewed at this festival.
             */
            totalSize?: number;
        };
        /** @description Response message for ListTastingSummaries. */
        ListTastingSummariesResponse: {
            /** @description Tasting counts for this page, one per tried drink. */
            tastingSummaries?: components["schemas"]["TastingSummary"][];
            /** @description Token for the next page; empty when there are no more results. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of drinks tried by at least one caller at this festival.
             */
            totalSize?: number;
        };
        /** @description Response message for ListTastings. */
        ListTastingsResponse: {
            /** @description The caller's tasting records for this page, one per tried drink. */
            tastings?: components["schemas"]["Tasting"][];
            /** @description Token for the next page; empty when there are no more results. */
            nextPageToken?: string;
            /**
             * Format: int32
             * @description Total number of drinks the caller has tried at this festival.
             */
            totalSize?: number;
        };
        /**
         * @description The caller's free-text tasting note for one drink at one festival.
         *
         *      Singleton resource — one per (caller, drink). The caller is implicit in the
         *      auth context. A note is independent of a Review: you can note without rating,
         *      or rate without noting.
         */
        Note: {
            /** @description Resource name: festivals/{festival}/drinks/{drink}/note. */
            name?: string;
            /** @description The caller's note text. Max 2000 Unicode characters. */
            content: string;
            /**
             * Format: date-time
             * @description When this note was last written.
             */
            readonly updateTime?: string;
        };
        /**
         * @description The caller's review of one drink at one festival: a star rating (1-5) and/or
         *      a "would recommend" answer.
         *
         *      Singleton resource — one per (caller, drink). The caller is implicit in the
         *      auth context; their identity never appears in the resource name, keeping
         *      device IDs private and making the sign-in upgrade transparent to clients.
         *
         *      Both signals are optional and independent: a caller can rate without
         *      answering the recommendation question, or vice versa.
         */
        Review: {
            /** @description Resource name: festivals/{festival}/drinks/{drink}/review. */
            name?: string;
            /**
             * Format: int32
             * @description Star rating, 1–5 inclusive. Absent if the caller has not set a star rating.
             */
            starRating?: number;
            /** @description Whether the caller would recommend this drink. Absent if not answered. */
            wouldRecommend?: boolean;
            /**
             * Format: date-time
             * @description When this review was last written.
             */
            readonly updateTime?: string;
        };
        /**
         * @description Computed, read-only aggregate of all callers' reviews for one drink.
         *
         *      Keyed by drink under the festival so the whole festival can be fetched in
         *      one paginated call for list/grid views.
         */
        ReviewSummary: {
            /** @description Resource name: festivals/{festival}/reviewSummaries/{drink}. */
            name?: string;
            /**
             * Format: int32
             * @description Number of callers who have submitted a star rating.
             */
            readonly ratingCount?: number;
            /**
             * Format: double
             * @description Mean star rating across all callers (1.0–5.0); 0 when rating_count is 0.
             */
            readonly averageRating?: number;
            /**
             * Format: int32
             * @description Number of callers who have answered the "would recommend" question.
             */
            readonly responseCount?: number;
            /**
             * Format: int32
             * @description Number of callers who answered "yes" to the recommendation question.
             */
            readonly recommendCount?: number;
            /**
             * Format: double
             * @description Fraction of responses (0.0–1.0) that would recommend; 0 when
             *      response_count is 0.
             */
            readonly recommendRate?: number;
        };
        /**
         * @description A record that the caller has tried a drink at a festival.
         *
         *      Singleton resource — one per (caller, drink). The caller is implicit in the
         *      auth context. `pours` tracks how many times the caller has had this drink at
         *      the festival (e.g. returned for a second half-pint); absent means one pour.
         */
        Tasting: {
            /** @description Resource name: festivals/{festival}/drinks/{drink}/tasting. */
            name?: string;
            /**
             * Format: int32
             * @description How many times the caller has had this drink. Absent means one pour.
             *      Must be >= 1 when present.
             */
            pours?: number;
            /**
             * Format: date-time
             * @description When the caller first tried this drink.
             */
            readonly createTime?: string;
            /**
             * Format: date-time
             * @description When this record was last updated.
             */
            readonly updateTime?: string;
        };
        /**
         * @description Computed, read-only aggregate of how many callers have tried a drink.
         *
         *      Useful for social discovery ("N people have tried this"). Keyed by drink
         *      under the festival, matching the ReviewSummary pattern.
         */
        TastingSummary: {
            /** @description Resource name: festivals/{festival}/tastingSummaries/{drink}. */
            name?: string;
            /**
             * Format: int32
             * @description Number of distinct callers who have logged a tasting for this drink.
             */
            readonly tasterCount?: number;
            /**
             * Format: int32
             * @description Total pours logged across all callers.
             */
            readonly totalPours?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MyFestivalService_ListBookmarks: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of bookmarks to return. The server default returns all of
                 *      the caller's bookmarks for the festival in a single page (festival drink
                 *      counts are bounded). Set explicitly to paginate.
                 */
                pageSize?: number;
                /** @description Page token from a previous ListBookmarks response. */
                pageToken?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBookmarksResponse"];
                };
            };
        };
    };
    MyFestivalService_GetBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
        };
    };
    MyFestivalService_DeleteBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MyFestivalService_UpdateBookmark: {
        parameters: {
            query?: {
                /** @description Fields to update. Omit to replace all writable fields. */
                updateMask?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Bookmark"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bookmark"];
                };
            };
        };
    };
    MyFestivalService_GetNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    MyFestivalService_DeleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MyFestivalService_UpdateNote: {
        parameters: {
            query?: {
                /** @description Fields to update. Omit to replace all writable fields. */
                updateMask?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Note"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
        };
    };
    MyFestivalService_GetReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
        };
    };
    MyFestivalService_DeleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MyFestivalService_UpdateReview: {
        parameters: {
            query?: {
                /**
                 * @description Fields to update. Omit to replace all writable fields. Specify
                 *      `star_rating` or `would_recommend` individually to update one signal
                 *      without affecting the other.
                 */
                updateMask?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
        };
    };
    MyFestivalService_GetTasting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tasting"];
                };
            };
        };
    };
    MyFestivalService_DeleteTasting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MyFestivalService_UpdateTasting: {
        parameters: {
            query?: {
                /**
                 * @description Fields to update. Omit to replace all writable fields. Specify `pours`
                 *      to update the pour count without affecting other fields.
                 */
                updateMask?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The drink id. */
                drink: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tasting"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tasting"];
                };
            };
        };
    };
    MyFestivalService_ListNotes: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of notes to return. The server default returns all of the
                 *      caller's notes for the festival in a single page (festival drink counts
                 *      are bounded). Set explicitly to paginate.
                 */
                pageSize?: number;
                /** @description Page token from a previous ListNotes response. */
                pageToken?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListNotesResponse"];
                };
            };
        };
    };
    MyFestivalService_ListReviewSummaries: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of summaries to return. The server default returns all
                 *      summaries for the festival in a single page (drink counts are bounded).
                 *      Set explicitly to paginate.
                 */
                pageSize?: number;
                /** @description Page token from a previous ListReviewSummaries response. */
                pageToken?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListReviewSummariesResponse"];
                };
            };
        };
    };
    MyFestivalService_GetReviewSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The reviewSummary id. */
                reviewSummary: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
        };
    };
    MyFestivalService_ListReviews: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of reviews to return. The server default returns all of the
                 *      caller's reviews for the festival in a single page (festival drink counts
                 *      are bounded). Set explicitly to paginate.
                 */
                pageSize?: number;
                /** @description Page token from a previous ListReviews response. */
                pageToken?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListReviewsResponse"];
                };
            };
        };
    };
    MyFestivalService_ListTastingSummaries: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of summaries to return. The server default returns all
                 *      summaries for the festival in a single page (drink counts are bounded).
                 *      Set explicitly to paginate.
                 */
                pageSize?: number;
                /** @description Page token from a previous ListTastingSummaries response. */
                pageToken?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTastingSummariesResponse"];
                };
            };
        };
    };
    MyFestivalService_GetTastingSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
                /** @description The tastingSummary id. */
                tastingSummary: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TastingSummary"];
                };
            };
        };
    };
    MyFestivalService_ListTastings: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of tastings to return. The server default returns all of
                 *      the caller's tastings for the festival in a single page (festival drink
                 *      counts are bounded). Set explicitly to paginate.
                 */
                pageSize?: number;
                /** @description Page token from a previous ListTastings response. */
                pageToken?: string;
            };
            header?: never;
            path: {
                /** @description The festival id. */
                festival: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTastingsResponse"];
                };
            };
        };
    };
}
