// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAelcjH0MOxri-NUGHsICJCYc7onYE0tSY',
    appId: '1:603123622258:web:f3e5565857638a10183deb',
    messagingSenderId: '603123622258',
    projectId: 'cambridge-beer-festival-app',
    authDomain: 'cambridge-beer-festival-app.firebaseapp.com',
    storageBucket: 'cambridge-beer-festival-app.firebasestorage.app',
    measurementId: 'G-PBL9P32S41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZjIiBepeBQ8187zJFQPT7uMCA9MMTumo',
    appId: '1:603123622258:android:0e6c04d80dfbecad183deb',
    messagingSenderId: '603123622258',
    projectId: 'cambridge-beer-festival-app',
    storageBucket: 'cambridge-beer-festival-app.firebasestorage.app',
  );

}