// Mocks generated by Mockito 5.4.6 from annotations
// in cambridge_beer_festival/test/domain/repositories/api_drink_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cambridge_beer_festival/models/models.dart' as _i6;
import 'package:cambridge_beer_festival/services/analytics_service.dart' as _i7;
import 'package:cambridge_beer_festival/services/beer_api_service.dart' as _i2;
import 'package:firebase_analytics/firebase_analytics.dart' as _i3;
import 'package:firebase_crashlytics/firebase_crashlytics.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFestivalDrinksResult_1 extends _i1.SmartFake
    implements _i2.FestivalDrinksResult {
  _FakeFestivalDrinksResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAnalytics_2 extends _i1.SmartFake
    implements _i3.FirebaseAnalytics {
  _FakeFirebaseAnalytics_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseCrashlytics_3 extends _i1.SmartFake
    implements _i4.FirebaseCrashlytics {
  _FakeFirebaseCrashlytics_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BeerApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeerApiService extends _i1.Mock implements _i2.BeerApiService {
  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
            returnValueForMissingStub: _FakeDuration_0(
              this,
              Invocation.getter(#timeout),
            ),
          )
          as Duration);

  @override
  _i5.Future<List<_i6.Drink>> fetchDrinks(
    _i6.Festival? festival,
    String? beverageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDrinks, [festival, beverageType]),
            returnValue: _i5.Future<List<_i6.Drink>>.value(<_i6.Drink>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.Drink>>.value(
              <_i6.Drink>[],
            ),
          )
          as _i5.Future<List<_i6.Drink>>);

  @override
  _i5.Future<_i2.FestivalDrinksResult> fetchDrinksByType(
    _i6.Festival? festival,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDrinksByType, [festival]),
            returnValue: _i5.Future<_i2.FestivalDrinksResult>.value(
              _FakeFestivalDrinksResult_1(
                this,
                Invocation.method(#fetchDrinksByType, [festival]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.FestivalDrinksResult>.value(
                  _FakeFestivalDrinksResult_1(
                    this,
                    Invocation.method(#fetchDrinksByType, [festival]),
                  ),
                ),
          )
          as _i5.Future<_i2.FestivalDrinksResult>);

  @override
  _i5.Future<List<_i6.Drink>> fetchAllDrinks(_i6.Festival? festival) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllDrinks, [festival]),
            returnValue: _i5.Future<List<_i6.Drink>>.value(<_i6.Drink>[]),
            returnValueForMissingStub: _i5.Future<List<_i6.Drink>>.value(
              <_i6.Drink>[],
            ),
          )
          as _i5.Future<List<_i6.Drink>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i7.AnalyticsService {
  @override
  _i3.FirebaseAnalytics get analytics =>
      (super.noSuchMethod(
            Invocation.getter(#analytics),
            returnValue: _FakeFirebaseAnalytics_2(
              this,
              Invocation.getter(#analytics),
            ),
            returnValueForMissingStub: _FakeFirebaseAnalytics_2(
              this,
              Invocation.getter(#analytics),
            ),
          )
          as _i3.FirebaseAnalytics);

  @override
  _i4.FirebaseCrashlytics get crashlytics =>
      (super.noSuchMethod(
            Invocation.getter(#crashlytics),
            returnValue: _FakeFirebaseCrashlytics_3(
              this,
              Invocation.getter(#crashlytics),
            ),
            returnValueForMissingStub: _FakeFirebaseCrashlytics_3(
              this,
              Invocation.getter(#crashlytics),
            ),
          )
          as _i4.FirebaseCrashlytics);

  @override
  _i5.Future<void> logAppLaunch() =>
      (super.noSuchMethod(
            Invocation.method(#logAppLaunch, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFestivalSelected(_i6.Festival? festival) =>
      (super.noSuchMethod(
            Invocation.method(#logFestivalSelected, [festival]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logCategoryFilter(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#logCategoryFilter, [category]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logStyleFilter(Set<String>? styles) =>
      (super.noSuchMethod(
            Invocation.method(#logStyleFilter, [styles]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logSortChange(String? sortType) =>
      (super.noSuchMethod(
            Invocation.method(#logSortChange, [sortType]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFavoriteAdded(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logFavoriteAdded, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFavoriteRemoved(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logFavoriteRemoved, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logTastedAdded(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logTastedAdded, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logTastedRemoved(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logTastedRemoved, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFestivalLogViewed() =>
      (super.noSuchMethod(
            Invocation.method(#logFestivalLogViewed, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFestivalLogAddToTry(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logFestivalLogAddToTry, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFestivalLogMarkTasted(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logFestivalLogMarkTasted, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFestivalLogMultipleTasting(
    _i6.Drink? drink,
    int? tastingCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logFestivalLogMultipleTasting, [
              drink,
              tastingCount,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logFestivalLogDeleteTimestamp(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logFestivalLogDeleteTimestamp, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logDrinkViewed(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logDrinkViewed, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logBreweryViewed(String? breweryName) =>
      (super.noSuchMethod(
            Invocation.method(#logBreweryViewed, [breweryName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logStyleViewed(String? style) =>
      (super.noSuchMethod(
            Invocation.method(#logStyleViewed, [style]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logRatingGiven(_i6.Drink? drink, int? rating) =>
      (super.noSuchMethod(
            Invocation.method(#logRatingGiven, [drink, rating]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logDrinkShared(_i6.Drink? drink) =>
      (super.noSuchMethod(
            Invocation.method(#logDrinkShared, [drink]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logError(
    Object? error,
    StackTrace? stackTrace, {
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logError,
              [error, stackTrace],
              {#reason: reason},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
