// Mocks generated by Mockito 5.4.6 from annotations
// in cambridge_beer_festival/test/domain/repositories/api_drink_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cambridge_beer_festival/models/models.dart' as _i4;
import 'package:cambridge_beer_festival/services/beer_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFestivalDrinksResult_1 extends _i1.SmartFake
    implements _i2.FestivalDrinksResult {
  _FakeFestivalDrinksResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BeerApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeerApiService extends _i1.Mock implements _i2.BeerApiService {
  @override
  Duration get timeout => (super.noSuchMethod(
        Invocation.getter(#timeout),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.getter(#timeout),
        ),
      ) as Duration);

  @override
  _i3.Future<List<_i4.Drink>> fetchDrinks(
    _i4.Festival? festival,
    String? beverageType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDrinks,
          [
            festival,
            beverageType,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Drink>>.value(<_i4.Drink>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Drink>>.value(<_i4.Drink>[]),
      ) as _i3.Future<List<_i4.Drink>>);

  @override
  _i3.Future<_i2.FestivalDrinksResult> fetchDrinksByType(
          _i4.Festival? festival) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDrinksByType,
          [festival],
        ),
        returnValue: _i3.Future<_i2.FestivalDrinksResult>.value(
            _FakeFestivalDrinksResult_1(
          this,
          Invocation.method(
            #fetchDrinksByType,
            [festival],
          ),
        )),
        returnValueForMissingStub: _i3.Future<_i2.FestivalDrinksResult>.value(
            _FakeFestivalDrinksResult_1(
          this,
          Invocation.method(
            #fetchDrinksByType,
            [festival],
          ),
        )),
      ) as _i3.Future<_i2.FestivalDrinksResult>);

  @override
  _i3.Future<List<_i4.Drink>> fetchAllDrinks(_i4.Festival? festival) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllDrinks,
          [festival],
        ),
        returnValue: _i3.Future<List<_i4.Drink>>.value(<_i4.Drink>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Drink>>.value(<_i4.Drink>[]),
      ) as _i3.Future<List<_i4.Drink>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
